sudo: false
language: ruby
cache: bundler
bundler: true
bundler_args: --without development production
rvm:
    - 2.2.2
addons:
    postgresql: 9.3
env:
    - RAILS_ENV=test
before_script:
    - bundle exec rake db:setup
script:
    - bundle exec rspec
